//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrlovKursovaya.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oborudovanie()
        {
            this.Remont = new HashSet<Remont>();
        }
    
        public int OborudovanieId { get; set; }
        public string OborudovanieName { get; set; }
        public string OborudovanieCount { get; set; }
        public string OborudovanieDescription { get; set; }
        public int TypeId { get; set; }
        public string Price { get; set; }
    
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remont> Remont { get; set; }
    }
}
