//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrlovKursovaya.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remont()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int RemontId { get; set; }
        public System.DateTime RemontDate { get; set; }
        public decimal RemontPrice { get; set; }
        public int OborudovanieId { get; set; }
        public int EmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Oborudovanie Oborudovanie { get; set; }
    }
}
